version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Login to dockerhub
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Build dockerfile
          command: |
            docker build --no-cache -t dockerhiscis/pharmm-api:latest .
      - run:
          name: Push Docker Image
          command: |
            docker push dockerhiscis/pharmm-api:latest
      - add_ssh_keys:
          fingerprints:
            - 'ff:78:f1:c9:e9:45:cc:c8:ca:45:3b:3b:fb:74:5a:df'

      - run:
          name: Deploy app to docker swarm via ssh
          command: |
            ssh -o StrictHostKeyChecking=no root@174.138.22.139 "cd /home/circle-deployment/pharmm-api-backend/ && docker pull dockerhiscis/pharmm-api:latest && docker-compose up -d"
workflows:
  basic-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main