version: 2.1
jobs:
  build-development:
    machine:
      image: ubuntu-2004:current
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Login to dockerhub
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Build dockerfile
          command: |
            docker build --no-cache -t dockerhiscis/pharmm-api:development-latest .
      - run:
          name: Push Docker Image
          command: |
            docker push dockerhiscis/pharmm-api:development-latest
      - add_ssh_keys:
          fingerprints:
            - 'ff:78:f1:c9:e9:45:cc:c8:ca:45:3b:3b:fb:74:5a:df'
      - run:
          name: Deploy app to server development
          command: |
            ssh -o StrictHostKeyChecking=no root@174.138.22.139 "cd /home/circle-deployment/pis-api-backend/ && docker pull dockerhiscis/pis-api:development-latest && docker-compose up -d"
            
  build-demo:
    machine:
      image: ubuntu-2004:current
    resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Login to dockerhub
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Build dockerfile
          command: |
            docker build --no-cache -t dockerhiscis/pharmm-api:$CIRCLE_SHA1 .
      - run:
          name: Push Docker Image
          command: |
            docker push dockerhiscis/pharmm-api:$CIRCLE_SHA1
            docker tag dockerhiscis/pharmm-api:$CIRCLE_SHA1 dockerhiscis/pharmm-api:demo-latest
            docker push dockerhiscis/pharmm-api:demo-latest
      - add_ssh_keys:
          fingerprints:
            - '55:7a:69:40:13:83:59:84:36:d6:82:bb:e5:f1:c8:a5'
      - run:
          name: Deploy app to server demo
          command: |
            ssh -o StrictHostKeyChecking=no his-admin@165.22.107.128 "cd /home/his-admin/pharmm-api/ && ./deploy.sh"
            
workflows:
  basic-workflow:
    jobs:
      - build-development:
          filters:
            branches:
              only:
                - development
      - build-demo:
          filters:
            branches:
              only:
                - demo