//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmm.API.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pharmm.API.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASMB.
        /// </summary>
        internal static string prefixKodeAssembly {
            get {
                return ResourceManager.GetString("prefixKodeAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MUT.
        /// </summary>
        internal static string prefixKodeMutasi {
            get {
                return ResourceManager.GetString("prefixKodeMutasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REQMUT.
        /// </summary>
        internal static string prefixKodeMutasiPermintaan {
            get {
                return ResourceManager.GetString("prefixKodeMutasiPermintaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISSUED.
        /// </summary>
        internal static string prefixKodePemakaianInternal {
            get {
                return ResourceManager.GetString("prefixKodePemakaianInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PO.
        /// </summary>
        internal static string prefixKodePemesanan {
            get {
                return ResourceManager.GetString("prefixKodePemesanan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PEMB.
        /// </summary>
        internal static string prefixKodePenerimaan {
            get {
                return ResourceManager.GetString("prefixKodePenerimaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPK.
        /// </summary>
        internal static string prefixKodeRepacking {
            get {
                return ResourceManager.GetString("prefixKodeRepacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETISSUED.
        /// </summary>
        internal static string prefixKodeReturPemakaianInternal {
            get {
                return ResourceManager.GetString("prefixKodeReturPemakaianInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETPEMB.
        /// </summary>
        internal static string prefixKodeReturPembelian {
            get {
                return ResourceManager.GetString("prefixKodeReturPembelian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHO.
        /// </summary>
        internal static string prefixKodeSetHargaOrder {
            get {
                return ResourceManager.GetString("prefixKodeSetHargaOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPJB.
        /// </summary>
        internal static string prefixKodeSPJB {
            get {
                return ResourceManager.GetString("prefixKodeSPJB", resourceCulture);
            }
        }
    }
}
